MRBC = mrbc
CC = gcc
SRCDIR = <%= @config["mruby_lib_dir"] %>
OBJDIR = <%= @config["c_lib_dir"] %>
MRUBYCSRCDIR = <%= @config["mrubyc_src_dir"] %>
SRCFILES = $(wildcard $(SRCDIR)/**/*.rb $(SRCDIR)/*.rb)
OBJS = $(subst $(SRCDIR),$(OBJDIR),$(patsubst %.rb,%.c,$(SRCFILES)))
TARGET = main

$(TARGET): $(OBJS) main.c
	$(CC) -DMRBC_DEBUG -o $@ $@.c $(MRUBYCSRCDIR)/*.c $(MRUBYCSRCDIR)/hal/*.c

$(OBJDIR)/%.c: $(SRCDIR)/%.rb
	@if [ ! -d $(dir $@) ]; \
		then echo "mkdir -p $(dir $@)"; mkdir -p $(dir $@); \
		fi
	$(MRBC) -E -B $(basename $(notdir $@)) -o $@ $<

clean:
	rm -f $(TARGET)
	rm -f $(OBJDIR)/**/*.c
